window.config = {
  legendUrls: {
    enkelbestemming: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/enkelbestemming/enkelbestemming.png",
    dubbelbestemming: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/dubbelbestemming/dubbelbestemming.png",
    bouwvlak: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/bouwvlak/bouwvlak.png",
    bouwaanduiding: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/bouwaanduiding/bouwaanduiding.png",
    figuur: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/figuur/figuur.png",
    functieaanduiding: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/functieaanduiding/functieaanduiding.png",
    gebiedsaanduiding: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/gebiedsaanduiding/gebiedsaanduiding.png",
    lettertekenaanduiding: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/lettertekenaanduiding/lettertekenaanduiding.png",
    maatvoering: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/maatvoering/maatvoering.png",
    plangebied: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/plangebied/plangebied.png",
    besluitgebied: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/besluitgebied_a/besluitgebied.png",
    besluitsubvlak: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/besluitsubvlak_a/besluitsubvlak.png",
    besluitvlak: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/besluitvlak_a/besluitvlak.png",
    bestemmingsplangebied: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/bestemmingsplangebied/plangebied.png",
    plangebied_pcp: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/plangebied_pcp/plangebied.png",
    provinciaalcomplex: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/provinciaalcomplex/complex.png",
    provinciaalgebied: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/provinciaalgebied/gebied.png",
    provinciaalplangebied: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/provinciaalplangebied/plangebied.png",
    structuurvisiecomplex: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/structuurvisiecomplex_g/complex.png",
    structuurvisiegebied: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/structuurvisiegebied_p/gebied.png",
    structuurvisieplangebied: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/structuurvisieplangebied_g/plangebied.png",
    structuurvisieverklaring: "https://service.pdok.nl/kadaster/plu/wms/v1_0/legend/structuurvisieverklaring_p/gebied.png"
  },
  Configurations: {
    Ruimtelijke_plannen: { 
      url: "https://service.pdok.nl/kadaster/adressen/wms/v1_0",
      service: "WMS",
      version: "1.3.0",
      request: "GetFeatureInfo",
      layers: "",
      styles: "",
      srs_or_crs: "crs",
      EPSG: "28992",
      format: "application/json",
      width: 1920,
      height: 1080,
      scale: 0.2
    },
    Ruimtelijke_plannen_bouwvlak: { 
      url: "https://service.pdok.nl/kadaster/plu/wms/v1_0",
      service: "WMS",
      version: "1.3.0",
      request: "GetMap",
      layers: "bouwvlak",
      styles: "",
      srs_or_crs: "CRS",
      EPSG: "28992",
      format: "image/jpeg",
      transparent: "false",
      width: 1920,
      height: 1080,
      scale: 0.2
    },
  },
};
